// Generated by Wrangler by running `wrangler types`

interface Env {
	ROADMAP_KV: KVNamespace;
	ENVIRONMENT: "staging" | "production";
	PROJECTS_DO: DurableObjectNamespace<import("./src/index").ProjectsDurableObject>;
	WORKER_LOGS: Fetcher;
}
